<?php
/**
 * Multisites.
 *
 * @copyright Albert Pérez Monfort (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Multisites
 * @author Albert Pérez Monfort <aperezm@xtec.cat>.
 * @link http://modulestudio.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

/**
 * Admin controller class.
 */
class Multisites_Controller_Base_Admin extends Zikula_AbstractController
{
    /**
     * Post initialise.
     *
     * Run after construction.
     *
     * @return void
     */
    protected function postInitialize()
    {
        // Set caching to false by default.
        $this->view->setCaching(Zikula_View::CACHE_DISABLED);
    }

    /**
     * This method is the default function handling the main area called without defining arguments.
     *
     *
     * @return mixed Output.
     */
    public function main()
    {
        // parameter specifying which type of objects we are treating
        $objectType = $this->request->query->filter('ot', 'site', FILTER_SANITIZE_STRING);
        
        $permLevel = ACCESS_ADMIN;
        $this->throwForbiddenUnless(SecurityUtil::checkPermission($this->name . '::', '::', $permLevel), LogUtil::getErrorMsgPermission());
        
        $redirectUrl = ModUtil::url($this->name, 'admin', 'view', array('lct' => 'admin'));
        
        return $this->redirect($redirectUrl);
    }
    
    /**
     * This is a custom method.
     *
     *
     * @return mixed Output.
     */
    public function manageUpdates()
    {
        $controllerHelper = new Multisites_Util_Controller($this->serviceManager);
        
        // parameter specifying which type of objects we are treating
        $objectType = $this->request->query->filter('ot', 'site', FILTER_SANITIZE_STRING);
        $utilArgs = array('controller' => 'admin', 'action' => 'manageUpdates');
        if (!in_array($objectType, $controllerHelper->getObjectTypes('controllerAction', $utilArgs))) {
            $objectType = $controllerHelper->getDefaultObjectType('controllerAction', $utilArgs);
        }
        $permLevel = ACCESS_ADMIN;
        $this->throwForbiddenUnless(SecurityUtil::checkPermission($this->name . ':' . ucfirst($objectType) . ':', '::', $permLevel), LogUtil::getErrorMsgPermission());
        /** TODO: custom logic */
        
        // return template
        return $this->view->fetch('admin/manageUpdates.tpl');
    }
    
    /**
     * This is a custom method.
     *
     *
     * @return mixed Output.
     */
    public function multiplyQueries()
    {
        $controllerHelper = new Multisites_Util_Controller($this->serviceManager);
        
        // parameter specifying which type of objects we are treating
        $objectType = $this->request->query->filter('ot', 'site', FILTER_SANITIZE_STRING);
        $utilArgs = array('controller' => 'admin', 'action' => 'multiplyQueries');
        if (!in_array($objectType, $controllerHelper->getObjectTypes('controllerAction', $utilArgs))) {
            $objectType = $controllerHelper->getDefaultObjectType('controllerAction', $utilArgs);
        }
        $permLevel = ACCESS_ADMIN;
        $this->throwForbiddenUnless(SecurityUtil::checkPermission($this->name . ':' . ucfirst($objectType) . ':', '::', $permLevel), LogUtil::getErrorMsgPermission());
        /** TODO: custom logic */
        
        // return template
        return $this->view->fetch('admin/multiplyQueries.tpl');
    }
    

    /**
     * This method cares for a redirect within an inline frame.
     *
     * @param string  $idPrefix    Prefix for inline window element identifier.
     * @param string  $commandName Name of action to be performed (create or edit).
     * @param integer $id          Id of created item (used for activating auto completion after closing the modal window).
     *
     * @return boolean Whether the inline redirect has been performed or not.
     */
    public function handleInlineRedirect()
    {
        $id = (int) $this->request->query->filter('id', 0, FILTER_VALIDATE_INT);
        $idPrefix = $this->request->query->filter('idPrefix', '', FILTER_SANITIZE_STRING);
        $commandName = $this->request->query->filter('commandName', '', FILTER_SANITIZE_STRING);
        if (empty($idPrefix)) {
            return false;
        }
        
        $this->view->assign('itemId', $id)
                   ->assign('idPrefix', $idPrefix)
                   ->assign('commandName', $commandName)
                   ->assign('jcssConfig', JCSSUtil::getJSConfig());
        
        $this->view->display('admin/inlineRedirectHandler.tpl');
        
        return true;
    }

    /**
     * This method takes care of the application configuration.
     *
     * @return string Output
     */
    public function config()
    {
        $this->throwForbiddenUnless(SecurityUtil::checkPermission($this->name . '::', '::', ACCESS_ADMIN));
        
        // Create new Form reference
        $view = FormUtil::newForm($this->name, $this);
        
        $templateName = 'admin/config.tpl';
        
        // Execute form using supplied template and page event handler
        return $view->execute($templateName, new Multisites_Form_Handler_Admin_Config());
    }
}
