<?php
/**
 * Multisites.
 *
 * @copyright Albert Pérez Monfort (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Multisites
 * @author Albert Pérez Monfort <aperezm@xtec.cat>.
 * @link http://modulestudio.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

/**
 * Special text input plugin for array fields.
 */
class Multisites_Form_Plugin_ArrayInput extends Zikula_Form_Plugin_TextInput
{
    /**
     * Create event handler.
     *
     * @param Zikula_Form_View $view Reference to Zikula_Form_View object.
     * @param array            &$params Parameters passed from the Smarty plugin function.
     *
     * @see    Zikula_Form_AbstractPlugin
     * @return void
     */
    public function create(Zikula_Form_View $view, &$params)
    {
        $params['textMode'] = 'multiline';

        parent::create($view, $params);
    }

    /**
     * Format the value to specific format.
     *
     * This override transfers the given array value into a text value.
     *
     * @param Zikula_Form_View $view  Reference to Zikula_Form_View object.
     * @param array            $value The value to format.
     *
     * @return string Formatted value.
     */
    public function formatValue(Zikula_Form_View $view, $value)
    {
        if (!is_array($value)) {
            return $value;
        }

        $value = $this->removeEmptyEntries($value);

        return implode("\n", $value);
    }

    /**
     * Parses a value.
     *
     * This override transfers the text back to an array.
     *
     * @param Zikula_Form_View $view Reference to Zikula_Form_View object.
     * @param string           $text Text.
     *
     * @return array Parsed value.
     */
    public function parseValue(Zikula_Form_View $view, $text)
    {
        $items = explode("\n", $text);

        return $this->removeEmptyEntries($items);
    }

    /**
     * Iterates over the given array and removes all empty entries.
     *
     * @param array array The given input array.
     *
     * @return array The cleaned array.
     */
    protected function removeEmptyEntries($array)
    {
        $items = $array;

        foreach ($items as $k => $v) {
            if (!empty($v)) {
                continue;
            }
            unset($items[$k]);
        }

        return $items;
    }
}
