<?php
/**
 * Multisites.
 *
 * @copyright Albert Pérez Monfort (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Multisites
 * @author Albert Pérez Monfort <aperezm@xtec.cat>.
 * @link http://modulestudio.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

/**
 * Relation selector plugin implementation class.
 */
class Multisites_Form_Plugin_RelationSelectorAutoComplete extends Multisites_Form_Plugin_Base_RelationSelectorAutoComplete
{
    // feel free to add your customisation here
}
