services:
    zikula_multisites_module.link_container:
        class: Zikula\MultisitesModule\Container\LinkContainer
        arguments:
            - "@translator.default"
            - "@router"
            - "@zikula_multisites_module.controller_helper"
            - "@zikula_multisites_module.permission_helper"
        tags: ['zikula.link_container']
    zikula_multisites_module.menu_builder:
        class: Zikula\MultisitesModule\Menu\MenuBuilder
        arguments:
            - "@translator.default"
            - "@knp_menu.factory"
            - "@event_dispatcher"
            - "@request_stack"
            - "@zikula_multisites_module.permission_helper"
            - "@zikula_users_module.current_user"
        calls:
            - [setDbalDriver, ["%doctrine.dbal.driver%"]]
        tags:
            - { name: knp_menu.menu_builder, method: createItemActionsMenu, alias: zikulaMultisitesMenuItemActions }
