zikulamultisitesmodule:
    # define routing support for these controllers
    resource: "@ZikulaMultisitesModule/Controller"
    # enable support for defining routes by annotations
    type: annotation
