modules/Multisites/templates/admin/config.tpl: config/templates/Multisites/admin/config.tpl
modules/Multisites/templates/admin/manageUpdates.tpl: config/templates/Multisites/admin/manageUpdates.tpl
modules/Multisites/templates/admin/multiplyQueries.tpl: config/templates/Multisites/admin/multiplyQueries.tpl
modules/Multisites/templates/admin/wizard.tpl: config/templates/Multisites/admin/wizard.tpl
modules/Multisites/templates/project/edit.tpl: config/templates/Multisites/project/edit.tpl
modules/Multisites/templates/project/view.tpl: config/templates/Multisites/project/view.tpl
modules/Multisites/templates/project/view_quickNav.tpl: config/templates/Multisites/project/view_quickNav.tpl
modules/Multisites/templates/site/delete.tpl: config/templates/Multisites/site/delete.tpl
modules/Multisites/templates/site/edit.tpl: config/templates/Multisites/site/edit.tpl
modules/Multisites/templates/site/iconsModule.tpl: config/templates/Multisites/site/iconsModule.tpl
modules/Multisites/templates/site/iconsTheme.tpl: config/templates/Multisites/site/iconsTheme.tpl
modules/Multisites/templates/site/manageExtensions.tpl: config/templates/Multisites/site/manageExtensions.tpl
modules/Multisites/templates/site/manageThemes.tpl: config/templates/Multisites/site/manageThemes.tpl
modules/Multisites/templates/site/view.tpl: config/templates/Multisites/site/view.tpl
modules/Multisites/templates/site/viewTools.tpl: config/templates/Multisites/site/viewTools.tpl
modules/Multisites/templates/template/edit.tpl: config/templates/Multisites/template/edit.tpl
modules/Multisites/templates/template/include_selectOne.tpl: config/templates/Multisites/template/include_selectOne.tpl
modules/Multisites/templates/template/reapply.tpl: config/templates/Multisites/template/reapply.tpl
modules/Multisites/templates/template/view.tpl: config/templates/Multisites/template/view.tpl
modules/Multisites/templates/template/view_quickNav.tpl: config/templates/Multisites/template/view_quickNav.tpl
