services:
    # Entity factory classes
    zikula_multisites_module.site_factory:
        class: Zikula\MultisitesModule\Entity\Factory\SiteFactory
        arguments: ["@doctrine.orm.entity_manager", Zikula\MultisitesModule\Entity\SiteEntity]
    
    zikula_multisites_module.template_factory:
        class: Zikula\MultisitesModule\Entity\Factory\TemplateFactory
        arguments: ["@doctrine.orm.entity_manager", Zikula\MultisitesModule\Entity\TemplateEntity]
    
    zikula_multisites_module.siteExtension_factory:
        class: Zikula\MultisitesModule\Entity\Factory\SiteExtensionFactory
        arguments: ["@doctrine.orm.entity_manager", Zikula\MultisitesModule\Entity\SiteExtensionEntity]
    
    zikula_multisites_module.project_factory:
        class: Zikula\MultisitesModule\Entity\Factory\ProjectFactory
        arguments: ["@doctrine.orm.entity_manager", Zikula\MultisitesModule\Entity\ProjectEntity]
    
