services:
    # Form field types
    
    zikula_multisites_module.form.type.field.upload:
        class: Zikula\MultisitesModule\Form\Type\Field\UploadType
        arguments: ["@translator.default"]
        tags:
            - { name: form.type }
