services:
    # Form field types
    
    zikula_multisites_module.form.upload_type_extension:
        class: Zikula\MultisitesModule\Form\Extension\UploadTypeExtension
        arguments: ["@translator.default"]
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FileType }
