services:
    # Helper classes
    zikula_multisites_module.controller_helper:
        class: Zikula\MultisitesModule\Helper\ControllerHelper
        arguments: ["@service_container", "@translator.default", "@session", "@logger"]
    
    zikula_multisites_module.hook_helper:
        class: Zikula\MultisitesModule\Helper\HookHelper
        arguments: ["@hook_dispatcher"]
    
    zikula_multisites_module.image_helper:
        class: Zikula\MultisitesModule\Helper\ImageHelper
        arguments: ["@translator.default", "@session", "@zikula_extensions_module.api.variable"]
    
    zikula_multisites_module.listentries_helper:
        class: Zikula\MultisitesModule\Helper\ListEntriesHelper
        arguments: ["@translator.default"]
    
    zikula_multisites_module.model_helper:
        class: Zikula\MultisitesModule\Helper\ModelHelper
        arguments: ["@service_container"]
    
    zikula_multisites_module.selection_helper:
        class: Zikula\MultisitesModule\Helper\SelectionHelper
        arguments: ["@service_container", "@doctrine.orm.entity_manager", "@translator.default", "@zikula_multisites_module.controller_helper"]
    
    zikula_multisites_module.view_helper:
        class: Zikula\MultisitesModule\Helper\ViewHelper
        arguments: ["@service_container", "@translator.default"]
    
    zikula_multisites_module.workflow_helper:
        class: Zikula\MultisitesModule\Helper\WorkflowHelper
        arguments: ["@service_container", "@translator.default"]

    # Custom helper classes
    zikula_multisites_module.configurator_helper:
        class: Zikula\MultisitesModule\Helper\ConfiguratorHelper
        arguments: ["@session", "@translator.default", "@zikula_extensions_module.api.variable", "@request_stack", "@zikula.dynamic_config_dumper", "@zikula.cache_clearer"]
    
    zikula_multisites_module.siteextension_helper:
        class: Zikula\MultisitesModule\Helper\SiteExtensionHelper
        arguments: ["@session", "@translator.default", "@request_stack", "@twig", "@zikula_multisites_module.workflow_helper", "@zikula_multisites_module.system_helper"]
    
    zikula_multisites_module.system_helper:
        class: Zikula\MultisitesModule\Helper\SystemHelper
        arguments: ["@session", "@translator.default", "@zikula_extensions_module.api.variable"]
