services:
    # Helper services
    zikula_multisites_module.collection_filter_helper:
        class: Zikula\MultisitesModule\Helper\CollectionFilterHelper
        arguments:
            - "@request_stack"
            - "@zikula_multisites_module.permission_helper"
            - "@zikula_users_module.current_user"
            - "@=service('zikula_extensions_module.api.variable').get('ZikulaMultisitesModule', 'showOnlyOwnEntries', false)"
    
    zikula_multisites_module.controller_helper:
        class: Zikula\MultisitesModule\Helper\ControllerHelper
        arguments:
            - "@translator.default"
            - "@request_stack"
            - "@logger"
            - "@form.factory"
            - "@zikula_extensions_module.api.variable"
            - "@zikula_multisites_module.entity_factory"
            - "@zikula_multisites_module.collection_filter_helper"
            - "@zikula_multisites_module.model_helper"
            - "@zikula_multisites_module.image_helper"
        calls:
            - [setMultisitesParameters, ["%multisites%"]]
    
    zikula_multisites_module.entity_display_helper:
        class: Zikula\MultisitesModule\Helper\EntityDisplayHelper
        arguments:
            - "@translator.default"
            - "@zikula_multisites_module.listentries_helper"
    
    zikula_multisites_module.hook_helper:
        class: Zikula\MultisitesModule\Helper\HookHelper
        arguments:
            - "@hook_dispatcher"
    
    zikula_multisites_module.image_helper:
        class: Zikula\MultisitesModule\Helper\ImageHelper
        arguments:
            - "@translator.default"
            - "@session"
            - "@zikula_extensions_module.api.variable"
    
    zikula_multisites_module.listentries_helper:
        class: Zikula\MultisitesModule\Helper\ListEntriesHelper
        arguments:
            - "@translator.default"
    
    zikula_multisites_module.model_helper:
        class: Zikula\MultisitesModule\Helper\ModelHelper
        arguments:
            - "@zikula_multisites_module.entity_factory"
    
    zikula_multisites_module.permission_helper:
        class: Zikula\MultisitesModule\Helper\PermissionHelper
        arguments:
            - "@service_container"
            - "@request_stack"
            - "@zikula_permissions_module.api.permission"
            - "@zikula_users_module.current_user"
            - "@zikula_users_module.user_repository"
    
    zikula_multisites_module.upload_helper:
        class: Zikula\MultisitesModule\Helper\UploadHelper
        arguments:
            - "@translator.default"
            - "@session"
            - "@logger"
            - "@zikula_users_module.current_user"
            - "@=service('zikula_extensions_module.api.variable').getAll('ZikulaMultisitesModule')"
            - "%datadir%"
    
    zikula_multisites_module.view_helper:
        class: Zikula\MultisitesModule\Helper\ViewHelper
        arguments:
            - "@twig"
            - "@twig.loader"
            - "@request_stack"
            - "@zikula_extensions_module.api.variable"
            - "@zikula_core.common.theme.pagevars"
            - "@zikula_multisites_module.controller_helper"
            - "@zikula_multisites_module.permission_helper"
    
    zikula_multisites_module.workflow_helper:
        class: Zikula\MultisitesModule\Helper\WorkflowHelper
        arguments:
            - "@translator.default"
            - "@workflow.registry"
            - "@logger"
            - "@zikula_users_module.current_user"
            - "@zikula_multisites_module.entity_factory"
            - "@zikula_multisites_module.listentries_helper"
            - "@zikula_multisites_module.permission_helper"
