services:
    zikula_multisites_module.link_container:
        class: Zikula\MultisitesModule\Container\LinkContainer
        arguments: ["@translator.default", "@router", "@zikula_permissions_module.api.permission", "@zikula_multisites_module.controller_helper", "@zikula_users_module.current_user"]
        tags:
            - { name: zikula.link_container }
