imports:
  - { resource: 'appSettings.yml' }
  - { resource: 'menu.yml' }
  - { resource: 'entityFactory.yml' }
  - { resource: 'eventSubscriber.yml' }
  - { resource: 'validators.yml' }
  - { resource: 'formFields.yml' }
  - { resource: 'forms.yml' }
  - { resource: 'helpers.yml' }
  - { resource: 'hooks.yml' }
  - { resource: 'twig.yml' }
  - { resource: 'logger.yml' }
  - { resource: 'customServices.yml' }

parameters:
    liip_imagine.cache.signer.class: Zikula\MultisitesModule\Imagine\Cache\DummySigner
