imports:
  - { resource: 'uploadHandler.yml' }
  - { resource: 'linkContainer.yml' }
  - { resource: 'entityFactories.yml' }
  - { resource: 'eventSubscriber.yml' }
  - { resource: 'formFields.yml' }
  - { resource: 'forms.yml' }
  - { resource: 'helpers.yml' }
  - { resource: 'twig.yml' }
  - { resource: 'logger.yml' }

parameters:
    liip_imagine.cache.signer.class: Zikula\MultisitesModule\Imagine\Cache\DummySigner
