<?php
/**
 * Multisites.
 *
 * @copyright Albert Pérez Monfort (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Multisites
 * @author Albert Pérez Monfort <aperezm@xtec.cat>.
 * @link http://modulestudio.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

/**
 * This event handler cares for replacing parameter placeholders by concrete values.
 */
class Multisites_EventHandlers_ReplaceParameters extends Zikula_AbstractEventHandler
{
    /**
     * Setup handler definitions.
     *
     * @return void
     */
    protected function setupHandlerDefinitions()
    {
        $this->addHandlerDefinition('theme.postfetch', 'handler');
    }

    /**
     * Event handler here.
     *
     * @param Zikula_Event $event Event handler.
     *
     * @return void
     */
    public function handler(Zikula_Event $event)
    {
        // replace parameter placeholders by concrete values
        $parameters = ModUtil::getVar('Multisites');
        if (count($parameters) < 1) {
            return;
        }

        $delimiter = '###';
        $output = $event->getData();

        foreach ($parameters as $paramName => $paramValue) {
            if (strpos($paramName, 'parameterValue') === false) {
                // normal modvar
                continue;
            }

            $placeholder = $delimiter . strtoupper(str_replace('parameterValue', '', $paramName)) . $delimiter;
            $output = str_replace($placeholder, $paramValue, $output);
        }

        $event->setData($output);
    }
}