<?php
/**
 * Multisites.
 *
 * @copyright Albert Pérez Monfort (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Multisites
 * @author Albert Pérez Monfort <aperezm@xtec.cat>.
 * @link http://modulestudio.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

/**
 * Repository class used to implement own convenience methods for performing certain DQL queries.
 *
 * This is the concrete repository class for template entities.
 */
class Multisites_Entity_Repository_Template extends Multisites_Entity_Repository_Base_Template
{
    /**
     * Returns an array of additional template variables for view quick navigation forms.
     *
     * @param string $context Usage context (allowed values: controllerAction, api, actionHandler, block, contentType).
     * @param array  $args    Additional arguments.
     *
     * @return array List of template variables to be assigned.
     */
    protected function getViewQuickNavParameters($context = '', $args = array())
    {
        $parameters = parent::getViewQuickNavParameters($context, $args);

        $parameters['projects'] = isset($this->controllerArguments['projects']) ? $this->controllerArguments['projects'] : FormUtil::getPassedValue('projects', 0, 'GET');

        return $parameters;
    }

    /**
     * Adds quick navigation related filter options as where clauses.
     *
     * @param Doctrine\ORM\QueryBuilder $qb Query builder to be enhanced.
     *
     * @return Doctrine\ORM\QueryBuilder Enriched query builder instance.
     */
    public function addCommonViewFilters(QueryBuilder $qb)
    {
        $currentFunc = FormUtil::getPassedValue('func', 'main', 'GETPOST');
        if ($currentFunc == 'edit') {
            return $qb;
        }

        $parameters = $this->getViewQuickNavParameters('', array());
        foreach ($parameters as $k => $v) {
            if ($k == 'projects') {
                if ($v > 0 && strpos($qb->getDql(), 'tblTemplates') !== false) {
                    $qb->andWhere(':projects MEMBER OF tbl.templates')
                       ->setParameter('projects', $v);
                }
            } elseif ($k == 'catId') {
                // single category filter
                if ($v > 0) {
                    $qb->andWhere('tblCategories.category = :category')
                       ->setParameter('category', $v);
                }
            } elseif ($k == 'catIdList') {
                // multi category filter
                /* old
                $qb->andWhere('tblCategories.category IN (:categories)')
                   ->setParameter('categories', $v);
                 */
                $qb = ModUtil::apiFunc('Multisites', 'category', 'buildFilterClauses', array('qb' => $qb, 'ot' => 'template', 'catids' => $v));
            } elseif (in_array($k, array('q', 'searchterm'))) {
                // quick search
                if (!empty($v)) {
                    $qb = $this->addSearchFilter($qb, $v);
                }
            } else {
                // field filter
                if ((!is_numeric($v) && $v != '') || (is_numeric($v) && $v > 0)) {
                    if ($k == 'workflowState' && substr($v, 0, 1) == '!') {
                        $qb->andWhere('tbl.' . $k . ' != :' . $k)
                           ->setParameter($k, substr($v, 1, strlen($v)-1));
                    } elseif (substr($v, 0, 1) == '%') {
                        $qb->andWhere('tbl.' . $k . ' LIKE :' . $k)
                           ->setParameter($k, '%' . $v . '%');
                    } else {
                        $qb->andWhere('tbl.' . $k . ' = :' . $k)
                           ->setParameter($k, $v);
                   }
                }
            }
        }

        $qb = $this->applyDefaultFilters($qb, $parameters);

        return $qb;
    }
}
