<?php
/**
 * Multisites.
 *
 * @copyright Albert P?rez Monfort (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Albert P?rez Monfort <aperezm@xtec.cat>.
 * @link http://modulestudio.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.1 (http://modulestudio.de).
 */

namespace Zikula\MultisitesModule\Listener;

use Zikula\MultisitesModule\Listener\Base\AbstractEntityLifecycleListener;

use FormUtil;
use ServiceUtil;
use Zikula\MultisitesModule\Entity\ProjectEntity;
use Zikula\MultisitesModule\Entity\SiteEntity;
use Zikula\MultisitesModule\Entity\TemplateEntity;

/**
 * Event subscriber implementation class for entity lifecycle events.
 */
class EntityLifecycleListener extends AbstractEntityLifecycleListener
{
    /**
     * {@inheritdoc}
     */
    public function preRemove(LifecycleEventArgs $args)
    {
        $entity = $args->getObject();
        if (!$this->isEntityManagedByThisBundle($entity) || !method_exists($entity, 'get_objectType')) {
            return;
        }

        if ($entity instanceof SiteEntity) {
            $deleteDatabase = FormUtil::getPassedValue('deleteDatabase', 0, 'POST', FILTER_VALIDATE_BOOLEAN);
            $deleteFiles = FormUtil::getPassedValue('deleteFiles', 0, 'POST', FILTER_VALIDATE_BOOLEAN);

            $serviceManager = ServiceUtil::getManager();
            $systemHelper = $serviceManager->get('zikula_multisites_module.system_helper');
            $flashBag = $serviceManager->get('session')->getFlashBag();

            if ($deleteDatabase == 1) {
                // delete the database
                if (!$systemHelper->deleteDatabase($this->getDatabaseData())) {
                    $flashBag->add('error', $serviceManager->get('translator.default')->__('Error during deleting the database.'));

                    return false;
                }
            }
            if ($deleteFiles == 1) {
                // delete the site files and directories
                $msConfig = $serviceManager->getParameter('multisites');
                $siteFolder = $msConfig['files_real_path'] . '/' . $this->getSiteAlias();
                if (!$systemHelper->deleteDir($siteFolder)) {
                    $flashBag->add('error', $serviceManager->get('translator.default')->__('Error during deleting the site files directory.'));

                    return false;
                }
            }
        }

        return parent::preRemove($args);
    }

    /**
     * {@inheritdoc}
     */
    public function postRemove(LifecycleEventArgs $args)
    {
        $entity = $args->getObject();
        if (!$this->isEntityManagedByThisBundle($entity) || !method_exists($entity, 'get_objectType')) {
            return;
        }

        if ($entity instanceof ProjectEntity || $entity instanceof TemplateEntity || $entity instanceof SiteEntity) {
            $serviceManager = ServiceUtil::getManager();
            $systemHelper = $serviceManager->get('zikula_multisites_module.system_helper');

            // update db config removing all obsolete databases
            if (!$systemHelper->updateDatabaseConfigFile()) {
                $flashBag = $serviceManager->get('session')->getFlashBag();
                $flashBag->add('error', $serviceManager->get('translator.default')->__('Error! Updating the database configuration file failed.'));

                return false;
            }
        }

        if ($entity instanceof TemplateEntity) {
            // delete sql file only if it is not referenced by any other template
            $sqlFileIsRequired = $entity->isSqlFileReferencedByOtherTemplates();
            if ($sqlFileIsRequired) {
                return;
            }
        }

        parent::postRemove($args);
    }

    /**
     * {@inheritdoc}
     */
    public function postPersist(LifecycleEventArgs $args)
    {
        $entity = $args->getObject();
        if (!$this->isEntityManagedByThisBundle($entity) || !method_exists($entity, 'get_objectType')) {
            return;
        }

        if ($entity instanceof SiteEntity) {
            $serviceManager = ServiceUtil::getManager();
            $systemHelper = $serviceManager->get('zikula_multisites_module.system_helper');
            $flashBag = $serviceManager->get('session')->getFlashBag();

            // update db config adding the new database
            if (!$systemHelper->updateDatabaseConfigFile()) {
                $flashBag->add('error', $serviceManager->get('translator.default')->__('Error! Updating the database configuration file failed.'));

                return false;
            }

            // save the site module into the Multisites database
            $extensionHelper = $serviceManager->get('zikula_multisites_module.siteextension_helper');
            if (!$extensionHelper->saveSiteModulesIntoOwnDb($this)) {
                $flashBag->add('error', $serviceManager->get('translator.default')->__('Error! Storing the site modules in the Multisites database failed.'));

                return false;
            }
        }

        parent::postPersist($args);
    }

    /**
     * {@inheritdoc}
     */
    public function postUpdate(LifecycleEventArgs $args)
    {
        $entity = $args->getObject();
        if (!$this->isEntityManagedByThisBundle($entity) || !method_exists($entity, 'get_objectType')) {
            return;
        }

        if ($entity instanceof SiteEntity) {
            $serviceManager = ServiceUtil::getManager();
            $systemHelper = $serviceManager->get('zikula_multisites_module.system_helper');

            // update db config adding the new database
            if (!$systemHelper->updateDatabaseConfigFile()) {
                $flashBag = $serviceManager->get('session')->getFlashBag();
                $flashBag->add('error', $serviceManager->get('translator.default')->__('Error! Updating the database configuration file failed.'));

                return false;
            }
        }

        parent::postUpdate($args);
    }
}
