<?php

/**
 * Multisites.
 *
 * @copyright Albert Pérez Monfort (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Albert Pérez Monfort <aperezm@xtec.cat>.
 *
 * @see https://modulestudio.de
 * @see https://ziku.la
 *
 * @version Generated by ModuleStudio 1.5.0 (https://modulestudio.de).
 */

namespace Zikula\MultisitesModule\Listener;

use Zikula\MultisitesModule\Listener\Base\AbstractUserListener;

/**
 * Event handler implementation class for user-related events.
 */
class UserListener extends AbstractUserListener
{
    // feel free to enhance the parent methods
}
