<?php

/**
 * Multisites.
 *
 * @copyright Albert Pérez Monfort (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Albert Pérez Monfort <aperezm@xtec.cat>.
 * @see https://modulestudio.de
 * @see https://ziku.la
 * @version Generated by ModuleStudio 1.5.0 (https://modulestudio.de).
 */

namespace Zikula\MultisitesModule\Helper;

use Zikula\MultisitesModule\Helper\Base\AbstractViewHelper;

/**
 * Helper implementation class for view layer methods.
 */
class ViewHelper extends AbstractViewHelper
{
    // feel free to add your own convenience methods here
}
