<?php
/**
 * Multisites.
 *
 * @copyright Albert Pérez Monfort (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Albert Pérez Monfort <aperezm@xtec.cat>.
 * @link http://modulestudio.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

namespace Zikula\MultisitesModule\Form;

use Zikula\MultisitesModule\Form\Base\AbstractDeleteEntityType;

/**
 * Entity deletion form type implementation class.
 */
class DeleteEntityType extends AbstractDeleteEntityType
{
    // feel free to extend the base form type class here
}
