<?php
/**
 * Multisites.
 *
 * @copyright Albert Pérez Monfort (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Multisites
 * @author Albert Pérez Monfort <aperezm@xtec.cat>.
 * @link http://modulestudio.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

/**
 * This is the Admin api helper class.
 */
class Multisites_Api_Admin extends Multisites_Api_Base_Admin
{
    /**
     * Returns available admin panel links.
     *
     * @return array Array of admin links.
     */
    public function getLinks()
    {
        $links = array();

        if (!SecurityUtil::checkPermission($this->name . '::', '::', ACCESS_ADMIN)) {
            return $links;
        }

        $links[] = array('url' => ModUtil::url($this->name, 'admin', 'view', array('ot' => 'project')),
            'text'  => $this->__('Projects'),
            'title' => $this->__('View projects'),
            'class' => 'z-icon-es-group'
        );

        $links[] = array('url' => ModUtil::url($this->name, 'admin', 'view', array('ot' => 'template')),
            'text'  => $this->__('Templates'),
            'title' => $this->__('View site templates'),
            'class' => 'z-icon-es-cubes'
        );

        $links[] = array('url' => ModUtil::url($this->name, 'admin', 'view', array('ot' => 'site')),
            'text'  => $this->__('Sites'),
            'title' => $this->__('View sites'),
            'class' => 'z-icon-es-log'
        );

        $links[] = array('url' => ModUtil::url($this->name, 'admin', 'manageUpdates'),
            'text'  => $this->__('Updates'),
            'title' => $this->__('Manage module updates'),
            'class' => 'z-icon-es-regenerate'
        );

        $links[] = array('url' => ModUtil::url($this->name, 'admin', 'multiplyQueries'),
            'text'  => $this->__('Queries'),
            'title' => $this->__('Execute mass queries in site databases'),
            'class' => 'z-icon-es-options'
        );

        $links[] = array('url' => ModUtil::url($this->name, 'admin', 'config'),
            'text'  => $this->__('Configuration'),
            'title' => $this->__('Configuration'),
            'class' => 'z-icon-es-config'
        );

        return $links;
    }
}
