<?php
/**
 * Multisites.
 *
 * @copyright Albert Pérez Monfort (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Albert Pérez Monfort <aperezm@xtec.cat>.
 * @link http://modulestudio.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

namespace Zikula\MultisitesModule\Form\Handler\Project;

use Zikula\MultisitesModule\Form\Handler\Project\Base\EditHandler as BaseEditHandler;

/**
 * This handler class handles the page events of the Form called by the zikulaMultisitesModule_project_edit() function.
 * It aims on the project object type.
 */
class EditHandler extends BaseEditHandler
{
    // feel free to extend the base handler class here
}
