<?php
/**
 * Multisites.
 *
 * @copyright Albert Pérez Monfort (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Albert Pérez Monfort <aperezm@xtec.cat>.
 * @link http://modulestudio.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.1 (http://modulestudio.de).
 */

namespace Zikula\MultisitesModule\Form\DataTransformer;

use Zikula\MultisitesModule\Form\DataTransformer\Base\AbstractUploadFileTransformer;

/**
 * Upload file transformer implementation class.
 *
 * This data transformer treats uploaded files.
 */
class UploadFileTransformer extends AbstractUploadFileTransformer
{
    // feel free to add your customisation here
}
