language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.2
    - php: nightly

services:
  - mysql

before_install:
    - if [[ "$TRAVIS_PHP_VERSION" != "nightly" ]] && [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]] && [ $(php -r "echo PHP_MINOR_VERSION;") -le 4 ]; then echo "extension = apc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;
    - if [[ "$TRAVIS_PHP_VERSION" != "nightly" ]] && [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then (pecl install -f memcached-2.1.0 && echo "extension = memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini) || echo "Let's continue without memcache extension"; fi;
    # - if [[ "$TRAVIS_PHP_VERSION" != "nightly" ]] && [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then php -i; fi;
    # Set the COMPOSER_ROOT_VERSION to the right version according to the branch being built
    - if [ "$TRAVIS_BRANCH" = "master" ]; then export COMPOSER_ROOT_VERSION=dev-master; else export COMPOSER_ROOT_VERSION="$TRAVIS_BRANCH".x-dev; fi;
    - composer self-update
    - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
    - mysql -e 'create database zk_test;'

install:
    - composer install
    - zip -qr ZikulaMultisitesModule.zip .
    - wget https://github.com/zikula/core/releases/download/2.0.10/2.0.tar.gz
    - tar -xpzf 2.0.tar.gz
    - rm 2.0.tar.gz
    - cd 2.0
    - php app/console zikula:install:start -n --database_user=root --database_name=zk_test --password=12345678 --email=admin@example.com --router:request_context:host=localhost
    - php app/console zikula:install:finish
    - cd modules
    - mkdir zikula
    - cd zikula
    - mkdir multisites-module
    - cd multisites-module
    - unzip -q ../../../../ZikulaMultisitesModule
    - cd  ../../..
    - php app/console bootstrap:bundles
    - mysql -e "INSERT INTO zk_test.modules (id, name, type, displayname, url, description, directory, version, capabilities, state, securityschema, core_min, core_max) VALUES (NULL, 'ZikulaMultisitesModule', '3', 'Multisites', 'multisites', 'Zikula Multisites manager.', 'zikula/multisites-module', '2.1.0', 'N;', '3', 'N;', '1.4.4', '2.0.0');"
    - php app/console cache:warmup

script:
    - php app/console lint:yaml modules/zikula/multisites-module/Resources
    - php app/console lint:twig @ZikulaMultisitesModule
    - phpunit --configuration modules/zikula/multisites-module/phpunit.xml.dist --coverage-text --coverage-clover=coverage.clover -v

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

before_deploy:
    - cd ..
    - mkdir release
    - cd release
    - unzip -q ../ZikulaMultisitesModule.zip
    - rm -Rf vendor
    - rm -Rf .git
    - composer install --no-dev --prefer-dist
    - rm auth.json
    - zip -qr ZikulaMultisitesModule.zip .

deploy:
  provider: releases
  api_key:
    secure: "" # Enter your api key here!
  file: ZikulaMultisitesModule.zip
  on:
    tags: true
    repo: zikula/Multisites

