<?php
/**
 * Multisites.
 *
 * @copyright Albert Pérez Monfort (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Albert Pérez Monfort <aperezm@xtec.cat>.
 * @link http://modulestudio.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.0.1 (https://modulestudio.de).
 */

namespace Zikula\MultisitesModule\Helper;

use Zikula\MultisitesModule\Helper\Base\AbstractControllerHelper;

/**
 * Helper implementation class for controller layer methods.
 */
class ControllerHelper extends AbstractControllerHelper
{
    /**
     * @var array
     */
    private $multisitesParameters;

    /**
     * Sets the multisites parameters.
     *
     * @param array $multisitesParameters
     */
    public function setMultisitesParameters(array $multisitesParameters = [])
    {
        $this->multisitesParameters = $multisitesParameters;
    }

    /**
     * @inheritDoc
     */
    public function addTemplateParameters($objectType = '', array $parameters = [], $context = '', array $args = [])
    {
        if (!in_array($context, ['controllerAction', 'api', 'actionHandler', 'block', 'contentType', 'mailz'])) {
            $context = 'controllerAction';
        }

        $parameters = parent::addTemplateParameters($objectType, $parameters, $context, $args);

        if ($objectType == 'site' && $context == 'controllerAction' && isset($args['action']) && $args['action'] == 'view') {
            $msConfig = $this->multisitesParameters;
            $parameters['wwwroot'] = isset($msConfig['wwwroot']) ? $msConfig['wwwroot'] : $this->request->getSchemeAndHttpHost() . $this->request->getBasePath();
            $parameters['basedOnDomains'] = $msConfig['based_on_domains'];
        }

        return $parameters;
    }
}
