<?php
/**
 * Multisites.
 *
 * @copyright Albert P?rez Monfort (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Albert P?rez Monfort <aperezm@xtec.cat>.
 * @link http://modulestudio.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

namespace Zikula\MultisitesModule\Base;

use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\Filesystem\Exception\IOExceptionInterface;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Zikula\Common\Translator\TranslatorInterface;
use Zikula\Common\Translator\TranslatorTrait;
use Zikula\ExtensionsModule\Api\VariableApi;
use Zikula\UsersModule\Api\CurrentUserApi;
use ServiceUtil;

/**
 * Upload handler base class.
 */
abstract class AbstractUploadHandler
{
    use TranslatorTrait;

    /**
     * @var CurrentUserApi
     */
    protected $currentUserApi;

    /**
     * @var VariableApi
     */
    protected $variableApi;

    /**
     * @var array List of object types with upload fields
     */
    protected $allowedObjectTypes;

    /**
     * @var array List of file types to be considered as images
     */
    protected $imageFileTypes;

    /**
     * @var array List of dangerous file types to be rejected
     */
    protected $forbiddenFileTypes;

    /**
     * Constructor initialising the supported object types.
    *
    * @param TranslatorInterface $translator     Translator service instance
    * @param CurrentUserApi      $currentUserApi CurrentUserApi service instance
    * @param VariableApi         $variableApi    VariableApi service instance
     */
    public function __construct(TranslatorInterface $translator, CurrentUserApi $currentUserApi, VariableApi $variableApi)
    {
        $this->setTranslator($translator);
        $this->currentUserApi = $currentUserApi;
        $this->variableApi = $variableApi;
        $this->allowedObjectTypes = ['site', 'template'];
        $this->imageFileTypes = ['gif', 'jpeg', 'jpg', 'png', 'swf'];
        $this->forbiddenFileTypes = ['cgi', 'pl', 'asp', 'phtml', 'php', 'php3', 'php4', 'php5', 'exe', 'com', 'bat', 'jsp', 'cfm', 'shtml'];
    }

    /**
     * Sets the translator.
     *
     * @param TranslatorInterface $translator Translator service instance
     */
    public function setTranslator(/*TranslatorInterface */$translator)
    {
        $this->translator = $translator;
    }

    /**
     * Process a file upload.
     *
     * @param string       $objectType Currently treated entity type
     * @param UploadedFile $file       The uploaded file
     * @param string       $fieldName  Name of upload field
     *
     * @return array Resulting file name and collected meta data
     */
    public function performFileUpload($objectType, $file, $fieldName)
    {
        $result = [
            'fileName' => '',
            'metaData' => []
        ];
    
        // check whether uploads are allowed for the given object type
        if (!in_array($objectType, $this->allowedObjectTypes)) {
            return $result;
        }
    
        // perform validation
        try {
            $this->validateFileUpload($objectType, $file, $fieldName);
        } catch (\Exception $e) {
            // skip this upload field
            return $result;
        }
    
        // build the file name
        $fileName = $file->getClientOriginalName();
        $fileNameParts = explode('.', $fileName);
        $extension = null !== $file->guessExtension() ? $file->guessExtension() : $file->guessClientExtension();
        if (null === $extension) {
            $extension = strtolower($fileNameParts[count($fileNameParts) - 1]);
        }
        $extension = str_replace('jpeg', 'jpg', $extension);
        $fileNameParts[count($fileNameParts) - 1] = $extension;
        $fileName = implode('.', $fileNameParts);
    
        $serviceManager = ServiceUtil::getManager();
        $controllerHelper = $serviceManager->get('zikula_multisites_module.controller_helper');
        $flashBag = $serviceManager->get('session')->getFlashBag();
        $logger = $serviceManager->get('logger');
    
        // retrieve the final file name
        try {
            $basePath = $controllerHelper->getFileBaseFolder($objectType, $fieldName);
        } catch (\Exception $e) {
            $flashBag->add('error', $e->getMessage());
            $logger->error('{app}: User {user} could not detect upload destination path for entity {entity} and field {field}.', ['app' => 'ZikulaMultisitesModule', 'user' => $this->currentUserApi->get('uname'), 'entity' => $objectType, 'field' => $fieldName]);
    
            return false;
        }
        $fileName = $this->determineFileName($objectType, $fieldName, $basePath, $fileName, $extension);
    
        $destinationFilePath = $basePath . $fileName;
        $targetFile = $file->move($basePath, $fileName);
    
        // validate image file
        $isImage = in_array($extension, $this->imageFileTypes);
        if ($isImage) {
            $imgInfo = getimagesize($destinationFilePath);
            if (!is_array($imgInfo) || !$imgInfo[0] || !$imgInfo[1]) {
                $flashBag->add('error', $this->__('Error! This file type seems not to be a valid image.'));
                $logger->error('{app}: User {user} tried to upload a file which is seems not to be a valid image.', ['app' => 'ZikulaMultisitesModule', 'user' => $this->currentUserApi->get('uname')]);
        
                return false;
            }
        }
    
        $isImage = in_array($extension, $this->imageFileTypes);
        if ($isImage) {
            // check if shrinking functionality is enabled
            $fieldSuffix = ucfirst($objectType) . ucfirst($fieldName);
            if (true === $this->variableApi->get('ZikulaMultisitesModule', 'enableShrinkingFor' . $fieldSuffix, false)) {
                // resize to allowed maximum size
                $thumbManager = $serviceManager->get('systemplugin.imagine.manager');
                $maxWidth = $this->variableApi->get('ZikulaMultisitesModule', 'shrinkWidth' . $fieldSuffix, 800);
                $maxHeight = $this->variableApi->get('ZikulaMultisitesModule', 'shrinkHeight' . $fieldSuffix, 600);
    
                $imgInfo = getimagesize($destinationFilePath);
                if ($imgInfo[0] > $maxWidth || $imgInfo[1] > $maxHeight) {
                    // create thumbnail image
                    $thumbFilePath = $thumbManager->getThumb($destinationFilePath, $maxWidth, $maxHeight);
    
                    // remove original image
                    unlink($destinationFilePath);
    
                    // rename thumbnail image to original image
                    rename($thumbFilePath, $destinationFilePath);
                }
            }
        }
    
        // collect data to return
        $result['fileName'] = $fileName;
        $result['metaData'] = $this->readMetaDataForFile($fileName, $destinationFilePath);
    
        return $result;
    }

    /**
     * Check if an upload file meets all validation criteria.
     *
     * @param string       $objectType Currently treated entity type
     * @param UploadedFile $file       Reference to data of uploaded file
     * @param string       $fieldName  Name of upload field
     *
     * @return boolean true if file is valid else false
     */
    protected function validateFileUpload($objectType, $file, $fieldName)
    {
        $serviceManager = ServiceUtil::getManager();
        $flashBag = $serviceManager->get('session')->getFlashBag();
        $logger = $serviceManager->get('logger');
    
        // check if a file has been uploaded properly without errors
        if ($file->getError() != UPLOAD_ERR_OK) {
            $flashBag->add('error', $file->getErrorMessage());
            $logger->error('{app}: User {user} tried to upload a file with errors: ' . $file->getErrorMessage(), ['app' => 'ZikulaMultisitesModule', 'user' => $this->currentUserApi->get('uname')]);
    
            return false;
        }
    
        // extract file extension
        $fileName = $file->getClientOriginalName();
        $extension = null !== $file->guessExtension() ? $file->guessExtension() : $file->guessClientExtension();
        if (null === $extension) {
            $fileNameParts = explode('.', $fileName);
            $extension = strtolower($fileNameParts[count($fileNameParts) - 1]);
        }
        $extension = str_replace('jpeg', 'jpg', $extension);
    
        // validate extension
        $isValidExtension = $this->isAllowedFileExtension($objectType, $fieldName, $extension);
        if (false === $isValidExtension) {
            $flashBag->add('error', $this->__('Error! This file type is not allowed. Please choose another file format.'));
            $logger->error('{app}: User {user} tried to upload a file with a forbidden extension ("{extension}").', ['app' => 'ZikulaMultisitesModule', 'user' => $this->currentUserApi->get('uname'), 'extension' => $extension]);
    
            return false;
        }
    
        return true;
    }

    /**
     * Read meta data from a certain file.
     *
     * @param string $fileName  Name of file to be processed
     * @param string $filePath  Path to file to be processed
     *
     * @return array collected meta data
     */
    public function readMetaDataForFile($fileName, $filePath)
    {
        $meta = [];
        if (empty($fileName)) {
            return $meta;
        }
    
        $extensionarr = explode('.', $fileName);
        $meta['extension'] = strtolower($extensionarr[count($extensionarr) - 1]);
        $meta['size'] = filesize($filePath);
        $meta['isImage'] = in_array($meta['extension'], $this->imageFileTypes) ? true : false;
    
        if (!$meta['isImage']) {
            return $meta;
        }
    
        if ($meta['extension'] == 'swf') {
            $meta['isImage'] = false;
        }
    
        $imgInfo = getimagesize($filePath);
        if (!is_array($imgInfo)) {
            return $meta;
        }
    
        $meta['width'] = $imgInfo[0];
        $meta['height'] = $imgInfo[1];
    
        if ($imgInfo[1] < $imgInfo[0]) {
            $meta['format'] = 'landscape';
        } elseif ($imgInfo[1] > $imgInfo[0]) {
            $meta['format'] = 'portrait';
        } else {
            $meta['format'] = 'square';
        }
    
        return $meta;
    }

    /**
     * Determines the allowed file extensions for a given object type.
     *
     * @param string $objectType Currently treated entity type
     * @param string $fieldName  Name of upload field
     * @param string $extension  Input file extension
     *
     * @return array the list of allowed file extensions
     */
    protected function isAllowedFileExtension($objectType, $fieldName, $extension)
    {
        // determine the allowed extensions
        $allowedExtensions = [];
        switch ($objectType) {
            case 'site':
                switch ($fieldName) {
                    case 'logo':
                        $allowedExtensions = ['gif', 'jpeg', 'jpg', 'png'];
                        break;
                    case 'favIcon':
                        $allowedExtensions = ['png', 'ico'];
                        break;
                    case 'parametersCsvFile':
                        $allowedExtensions = ['csv'];
                        break;
                }
                    break;
            case 'template':
                $allowedExtensions = ['sql', 'txt'];
                    break;
        }
    
        if (count($allowedExtensions) > 0) {
            if (!in_array($extension, $allowedExtensions)) {
                return false;
            }
        }
    
        if (in_array($extension, $this->forbiddenFileTypes)) {
            return false;
        }
    
        return true;
    }

    /**
     * Determines the final filename for a given input filename.
     *
     * It considers different strategies for computing the result.
     *
     * @param string $objectType Currently treated entity type
     * @param string $fieldName  Name of upload field
     * @param string $basePath   Base path for file storage
     * @param string $fileName   Input file name
     * @param string $extension  Input file extension
     *
     * @return string the resulting file name
     */
    protected function determineFileName($objectType, $fieldName, $basePath, $fileName, $extension)
    {
        $backupFileName = $fileName;
    
        $namingScheme = 0;
    
        switch ($objectType) {
            case 'site':
                switch ($fieldName) {
                    case 'logo':
                        $namingScheme = 0;
                        break;
                    case 'favIcon':
                        $namingScheme = 0;
                        break;
                    case 'parametersCsvFile':
                        $namingScheme = 0;
                        break;
                }
                    break;
            case 'template':
                $namingScheme = 0;
                    break;
        }
    
    
        $iterIndex = -1;
        do {
            if ($namingScheme == 0) {
                // original file name
                $fileNameCharCount = strlen($fileName);
                for ($y = 0; $y < $fileNameCharCount; $y++) {
                    if (preg_match('/[^0-9A-Za-z_\.]/', $fileName[$y])) {
                        $fileName[$y] = '_';
                    }
                }
                // append incremented number
                if ($iterIndex > 0) {
                    // strip off extension
                    $fileName = str_replace('.' . $extension, '', $backupFileName);
                    // add iterated number
                    $fileName .= (string) ++$iterIndex;
                    // readd extension
                    $fileName .= '.' . $extension;
                } else {
                    $iterIndex++;
                }
            } elseif ($namingScheme == 1) {
                // md5 name
                $fileName = md5(uniqid(mt_rand(), TRUE)) . '.' . $extension;
            } elseif ($namingScheme == 2) {
                // prefix with random number
                $fileName = $fieldName . mt_rand(1, 999999) . '.' . $extension;
            }
        }
        while (file_exists($basePath . $fileName)); // repeat until we have a new name
    
        // return the new file name
        return $fileName;
    }

    /**
     * Deletes an existing upload file.
     * For images the thumbnails are removed, too.
     *
     * @param object  $entity    Currently treated entity
     * @param string  $fieldName Name of upload field
     *
     * @return mixed Updated entity on success, else false
     */
    public function deleteUploadFile($entity, $fieldName)
    {
        $objectType = $entity->get_objectType();
        if (!in_array($objectType, $this->allowedObjectTypes)) {
            return false;
        }
    
        if (empty($entity[$fieldName])) {
            return $entity;
        }
    
        $serviceManager = ServiceUtil::getManager();
        $controllerHelper = $serviceManager->get('zikula_multisites_module.controller_helper');
    
        // remove the file
        $filePath = $entity[$fieldName]->getPathname();
        if (file_exists($filePath) && !unlink($filePath)) {
            return false;
        }
        $entity[$fieldName] = '';
        $entity[$fieldName . 'Meta'] = [];
    
        return $entity;
    }
}
