<?php

/**
 * Multisites.
 *
 * @copyright Albert Pérez Monfort (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Albert Pérez Monfort <aperezm@xtec.cat>.
 * @see https://modulestudio.de
 * @see https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

namespace Zikula\MultisitesModule\Event;

use Zikula\MultisitesModule\Event\Base\AbstractConfigureItemActionsMenuEvent;

/**
 * Event implementation class for extending item actions menu.
 */
class ConfigureItemActionsMenuEvent extends AbstractConfigureItemActionsMenuEvent
{
    // feel free to extend the event class here
}
