<?php
/**
 * Multisites.
 *
 * @copyright Albert Pérez Monfort (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Albert Pérez Monfort <aperezm@xtec.cat>.
 * @link https://modulestudio.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.3.2 (https://modulestudio.de).
 */

namespace Zikula\MultisitesModule\Form\Type\QuickNavigation;

use Zikula\MultisitesModule\Form\Type\QuickNavigation\Base\AbstractSiteQuickNavType;

/**
 * Site quick navigation form type implementation class.
 */
class SiteQuickNavType extends AbstractSiteQuickNavType
{
    // feel free to extend the base form type class here
}
