<?php
/**
 * Multisites.
 *
 * @copyright Albert Pérez Monfort (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Albert Pérez Monfort <aperezm@xtec.cat>.
 * @link http://modulestudio.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.1 (http://modulestudio.de).
 */

namespace Zikula\MultisitesModule\DependencyInjection;

use Zikula\MultisitesModule\DependencyInjection\Base\AbstractZikulaMultisitesExtension;

/**
 * Implementation class for service definition loader using the DependencyInjection extension.
 */
class ZikulaMultisitesExtension extends AbstractZikulaMultisitesExtension
{
    // custom enhancements can go here
}
