<?php

/**
 * Multisites.
 *
 * @copyright Albert Pérez Monfort (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Albert Pérez Monfort <aperezm@xtec.cat>.
 * @see https://modulestudio.de
 * @see https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

namespace Zikula\MultisitesModule\DependencyInjection;

use Zikula\MultisitesModule\DependencyInjection\Base\AbstractZikulaMultisitesExtension;

/**
 * DependencyInjection extension implementation class.
 */
class ZikulaMultisitesExtension extends AbstractZikulaMultisitesExtension
{
    // custom enhancements can go here
}
