<?php
/**
 * Multisites.
 *
 * @copyright Albert Pérez Monfort (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Multisites
 * @author Albert Pérez Monfort <aperezm@xtec.cat>.
 * @link http://modulestudio.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

/**
 * The multisitesObjectTypeSelector plugin provides items for a dropdown selector.
 *
 * Available parameters:
 *   - assign: If set, the results are assigned to the corresponding variable instead of printed out.
 *
 * @param  array            $params All attributes passed to this function from the template.
 * @param  Zikula_Form_View $view   Reference to the view object.
 *
 * @return string The output of the plugin.
 */
function smarty_function_multisitesObjectTypeSelector($params, $view)
{
    $dom = ZLanguage::getModuleDomain('Multisites');
    $result = array();

    $result[] = array('text' => __('Sites', $dom), 'value' => 'site');
    $result[] = array('text' => __('Templates', $dom), 'value' => 'template');
    $result[] = array('text' => __('Site extensions', $dom), 'value' => 'siteExtension');
    $result[] = array('text' => __('Projects', $dom), 'value' => 'project');

    if (array_key_exists('assign', $params)) {
        $view->assign($params['assign'], $result);

        return;
    }

    return $result;
}
