src/modules/Multisites/templates/site/view.tpl: config/templates/Multisites/site/view.tpl
src/modules/Multisites/templates/site/view_quickNav.tpl: config/templates/Multisites/site/view_quickNav.tpl
src/modules/Multisites/templates/site/view.csv.tpl: config/templates/Multisites/site/view.csv.tpl
src/modules/Multisites/templates/site/view.xml.tpl: config/templates/Multisites/site/view.xml.tpl
src/modules/Multisites/templates/site/include.xml.tpl: config/templates/Multisites/site/include.xml.tpl
src/modules/Multisites/templates/site/view.json.tpl: config/templates/Multisites/site/view.json.tpl
src/modules/Multisites/templates/template/view.tpl: config/templates/Multisites/template/view.tpl
src/modules/Multisites/templates/template/view_quickNav.tpl: config/templates/Multisites/template/view_quickNav.tpl
src/modules/Multisites/templates/template/view.csv.tpl: config/templates/Multisites/template/view.csv.tpl
src/modules/Multisites/templates/template/view.xml.tpl: config/templates/Multisites/template/view.xml.tpl
src/modules/Multisites/templates/template/include.xml.tpl: config/templates/Multisites/template/include.xml.tpl
src/modules/Multisites/templates/template/view.json.tpl: config/templates/Multisites/template/view.json.tpl
src/modules/Multisites/templates/siteExtension/view.tpl: config/templates/Multisites/siteExtension/view.tpl
src/modules/Multisites/templates/siteExtension/view_quickNav.tpl: config/templates/Multisites/siteExtension/view_quickNav.tpl
src/modules/Multisites/templates/siteExtension/view.csv.tpl: config/templates/Multisites/siteExtension/view.csv.tpl
src/modules/Multisites/templates/siteExtension/view.xml.tpl: config/templates/Multisites/siteExtension/view.xml.tpl
src/modules/Multisites/templates/siteExtension/include.xml.tpl: config/templates/Multisites/siteExtension/include.xml.tpl
src/modules/Multisites/templates/siteExtension/view.json.tpl: config/templates/Multisites/siteExtension/view.json.tpl
src/modules/Multisites/templates/project/view.tpl: config/templates/Multisites/project/view.tpl
src/modules/Multisites/templates/project/view_quickNav.tpl: config/templates/Multisites/project/view_quickNav.tpl
src/modules/Multisites/templates/project/view.csv.tpl: config/templates/Multisites/project/view.csv.tpl
src/modules/Multisites/templates/project/view.xml.tpl: config/templates/Multisites/project/view.xml.tpl
src/modules/Multisites/templates/project/include.xml.tpl: config/templates/Multisites/project/include.xml.tpl
src/modules/Multisites/templates/project/view.json.tpl: config/templates/Multisites/project/view.json.tpl
src/modules/Multisites/templates/admin/header.tpl: config/templates/Multisites/admin/header.tpl
src/modules/Multisites/templates/admin/footer.tpl: config/templates/Multisites/admin/footer.tpl
src/modules/Multisites/templates/admin/manageUpdates.tpl: config/templates/Multisites/admin/manageUpdates.tpl
src/modules/Multisites/templates/admin/multiplyQueries.tpl: config/templates/Multisites/admin/multiplyQueries.tpl
src/modules/Multisites/templates/site/delete.tpl: config/templates/Multisites/site/delete.tpl
src/modules/Multisites/templates/site/edit.tpl: config/templates/Multisites/site/edit.tpl
src/modules/Multisites/templates/site/manageExtensions.tpl: config/templates/Multisites/site/manageExtensions.tpl
src/modules/Multisites/templates/site/manageThemes.tpl: config/templates/Multisites/site/manageThemes.tpl
src/modules/Multisites/templates/site/iconsModule.tpl: config/templates/Multisites/site/iconsModule.tpl
src/modules/Multisites/templates/site/iconsTheme.tpl: config/templates/Multisites/site/iconsTheme.tpl
src/modules/Multisites/templates/site/inlineRedirectHandler.tpl: config/templates/Multisites/site/inlineRedirectHandler.tpl
src/modules/Multisites/templates/template/edit.tpl: config/templates/Multisites/template/edit.tpl
src/modules/Multisites/templates/template/inlineRedirectHandler.tpl: config/templates/Multisites/template/inlineRedirectHandler.tpl
src/modules/Multisites/templates/project/edit.tpl: config/templates/Multisites/project/edit.tpl
src/modules/Multisites/templates/project/inlineRedirectHandler.tpl: config/templates/Multisites/project/inlineRedirectHandler.tpl
src/modules/Multisites/templates/helper/include_standardfields_display.tpl: config/templates/Multisites/helper/include_standardfields_display.tpl
src/modules/Multisites/templates/helper/include_standardfields_edit.tpl: config/templates/Multisites/helper/include_standardfields_edit.tpl
src/modules/Multisites/templates/admin/config.tpl: config/templates/Multisites/admin/config.tpl
src/modules/Multisites/templates/admin/wizard.tpl: config/templates/Multisites/admin/wizard.tpl
src/modules/Multisites/templates/include_pdfheader.tpl: config/templates/Multisites/include_pdfheader.tpl
