<?php
/**
 * Multisites.
 *
 * @copyright Albert Pérez Monfort (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Albert Pérez Monfort <aperezm@xtec.cat>.
 * @link https://modulestudio.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio 1.3.2 (https://modulestudio.de).
 */

namespace Zikula\MultisitesModule\Entity\Factory;

use Zikula\MultisitesModule\Entity\Factory\Base\AbstractEntityFactory;

/**
 * Factory class used to create entities and receive entity repositories.
 */
class EntityFactory extends AbstractEntityFactory
{
    // feel free to customise the factory
}
