<?php
/**
 * Multisites.
 *
 * @copyright Albert Pérez Monfort (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Albert Pérez Monfort <aperezm@xtec.cat>.
 * @link http://modulestudio.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.1 (http://modulestudio.de).
 */

namespace Zikula\MultisitesModule\Entity\Factory;

use Zikula\MultisitesModule\Entity\Factory\Base\AbstractTemplateFactory;

/**
 * Factory class used to retrieve entity and repository instances.
 *
 * This is the concrete factory class for template entities.
 */
class TemplateFactory extends AbstractTemplateFactory
{
    // feel free to customise the manager
}
