<?php
/**
 * Multisites.
 *
 * @copyright Albert Pérez Monfort (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Albert Pérez Monfort <aperezm@xtec.cat>.
 * @link http://modulestudio.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.0.1 (http://modulestudio.de).
 */

namespace Zikula\MultisitesModule\Entity\Repository;

use Doctrine\ORM\QueryBuilder;
use Zikula\MultisitesModule\Entity\Repository\Base\AbstractProjectRepository;

/**
 * Repository class used to implement own convenience methods for performing certain DQL queries.
 *
 * This is the concrete repository class for project entities.
 */
class ProjectRepository extends AbstractProjectRepository
{
    /**
     * @inheritDoc
     */
    protected function addJoinsToSelection()
    {
        $selection = ', tblTemplates';//', tblSites, tblTemplates';
    
        return $selection;
    }
    
    /**
     * @inheritDoc
     */
    protected function addJoinsToFrom(QueryBuilder $qb)
    {
        //$qb->leftJoin('tbl.sites', 'tblSites');
        $qb->leftJoin('tbl.templates', 'tblTemplates');
    
        return $qb;
    }
}
