<?php
/**
 * Multisites.
 *
 * @copyright Albert Pérez Monfort (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Albert Pérez Monfort <aperezm@xtec.cat>.
 * @link https://modulestudio.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.2.0 (https://modulestudio.de).
 */

namespace Zikula\MultisitesModule\HookSubscriber;

use Zikula\MultisitesModule\HookSubscriber\Base\AbstractSiteFormAwareHookSubscriber;

/**
 * Implementation class for form aware hook subscriber.
 */
class SiteFormAwareHookSubscriber extends AbstractSiteFormAwareHookSubscriber
{
    // feel free to add your own convenience methods here
}
