<?php
/**
 * Multisites.
 *
 * @copyright Albert Pérez Monfort (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Multisites
 * @author Albert Pérez Monfort <aperezm@xtec.cat>.
 * @link http://modulestudio.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de) at Tue Oct 07 14:00:05 CEST 2014.
 */

/**
 * Version information implementation class.
 */
class Multisites_Version extends Multisites_Base_Version
{
    /**
     * Retrieves meta data information for this application.
     *
     * @return array List of meta data.
     */
    public function getMetaData()
    {
        $meta = parent::getMetaData();

        $meta['description'] = $this->__('Zikula Multisites module');
        $meta['displayname'] = $this->__('Multisites manager');

        return $meta;
    }
}
