<?php
/**
 * Multisites.
 *
 * @copyright Albert Pérez Monfort (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Albert Pérez Monfort <aperezm@xtec.cat>.
 * @link https://modulestudio.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio 1.3.2 (https://modulestudio.de).
 */

namespace Zikula\MultisitesModule\Event;

use Zikula\MultisitesModule\Event\Base\AbstractFilterTemplateEvent;

/**
 * Event implementation class for filtering template processing.
 */
class FilterTemplateEvent extends AbstractFilterTemplateEvent
{
    // feel free to extend the event class here
}
