<?php
/**
 * Multisites.
 *
 * @copyright Albert P?rez Monfort (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Albert P?rez Monfort <aperezm@xtec.cat>.
 * @link http://modulestudio.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

namespace Zikula\MultisitesModule\Event;

use Zikula\MultisitesModule\Event\Base\AbstractFilterProjectEvent;

/**
 * Event implementation class for filtering project processing.
 */
class FilterProjectEvent extends AbstractFilterProjectEvent
{
    // feel free to extend the event class here
}
