<?php
/**
 * Multisites.
 *
 * @copyright Albert Pérez Monfort (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Albert Pérez Monfort <aperezm@xtec.cat>.
 * @link https://modulestudio.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio 1.3.2 (https://modulestudio.de).
 */

namespace Zikula\MultisitesModule\Form\Type\Field;

use Zikula\MultisitesModule\Form\Type\Field\Base\AbstractUploadType;

/**
 * Upload field type implementation class.
 */
class UploadType extends AbstractUploadType
{
    // feel free to add your customisation here
}
