<?php
/**
 * Multisites.
 *
 * @copyright Albert Pérez Monfort (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Albert Pérez Monfort <aperezm@xtec.cat>.
 * @link http://modulestudio.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

namespace Zikula\MultisitesModule\Helper\Base;

use Zikula\Core\Doctrine\EntityAccess;
use Zikula\Core\Hook\ProcessHook;
use Zikula\Core\Hook\ValidationHook;
use Zikula\Core\Hook\ValidationProviders;
use Zikula_HookDispatcher
/**
 * Utility base class for hook related helper methods.
 */
class HookHelper
{
    /**
     * @var Zikula_HookDispatcher
     */
    protected $hookDispatcher;

    /**
     * Constructor.
     * Initialises member vars.
     *
     * @param Zikula_HookDispatcher $hookDispatcher Hook dispatcher service instance.
     *
     * @return void
     */
    public function __construct($hookDispatcher)
    {
        $this->hookDispatcher = $hookDispatcher;
    }

    /**
     * Calls validation hooks.
     *
     * @param EntityAccess $entity   The currently processed entity.
     * @param string       $hookType Name of hook type to be called.
     *
     * @return boolean Whether validation is passed or not.
     */
    public function callValidationHooks($entity, $hookType)
    {
        $isValid = true;
        $hookAreaPrefix = $entity->getHookAreaPrefix();
    
        $hook = new ValidationHook(new ValidationProviders());
        $validators = $this->dispatchHooks($hookAreaPrefix . '.' . $hookType, $hook)->getValidators();
    
        return !$validators->hasErrors();
    }

    /**
     * Calls process hooks.
     *
     * @param EntityAccess $entity The currently processed entity.
     * @param string       $hookType Name of hook type to be called.
     * @param RouteUrl            $url      The url object.
     */
    public function callProcessHooks($entity, $hookType, $url)
    {
        $hookAreaPrefix = $entity->getHookAreaPrefix();
    
        $hook = new ProcessHook($entity->createCompositeIdentifier(), $url);
        $this->dispatchHooks($hookAreaPrefix . '.' . $hookType, $hook);
    }

    /**
     * Dispatch hooks.
     *
     * @param Hook $hook Hook interface.
     *
     * @return Zikula\Component\HookDispatcher\Hook
     */
    public function dispatchHooks($name, Hook $hook)
    {
        return $this->hookDispatcher->dispatch($name, $hook);
    }
}
