name: Test module
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_USER: zikula
          MYSQL_PASSWORD: zikula
          MYSQL_DATABASE: zikula
          MYSQL_ROOT_PASSWORD: zikula
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - name: Checkout sources
      uses: actions/checkout@v1

    # see https://github.com/Guite/zikula-action
    - name: Build and test
      uses: guite/zikula-action@master
      with:
        vendor_name: Zikula
        module_name: Multisites
        module_version: '2.1.0'
        core_version: ZK20
        database_host: mysql
        database_port: 3306
        create_artifacts: true

    # see https://github.com/actions/upload-artifact
    - name: Upload release folder as artifact
      uses: actions/upload-artifact@master
      with:
        name: ZikulaMultisitesModule_v2.1.0
        path: './ZikulaMultisitesModule_v2.1.0'
