name: Test module
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: zikula
          MYSQL_DATABASE: zikula
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - name: Checkout sources
      uses: actions/checkout@v1

    # see https://github.com/Guite/zikula-action
    - name: Build and test
      uses: guite/zikula-action@master
      with:
        vendor_name: 'Zikula'
        module_name: 'Multisites'
        module_version: '2.1.0'
        core_version: 'ZK20'
        create_artifacts: true
      env:
        DATABASE_URL: mysql://root:zikula@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/zikula

    # see https://github.com/actions/upload-artifact
    - name: Upload tar archive as artifact
      uses: actions/upload-artifact@master
      with:
        name: tar-archive
        path: './ZikulaMultisitesModule_v2.1.0.tar.gz'
    - name: Upload zip archive as artifact
      uses: actions/upload-artifact@master
      with:
        name: zip-archive
        path: './ZikulaMultisitesModule_v2.1.0.zip'
